Repository wecode-bootcamp-korea/49-3rd-WEE.T-frontend, pull requests merged in 2023-10, with the labels that each got.

#3 style : 공통 common.scss, reset.scss 수정
  src/styles/common.scss
  src/styles/reset.scss
Labels: 멘토 리뷰 요청

#4 로그인 ui, 기능 구현
  .gitignore
  public/images/login_kakao.svg
  public/images/logo2.png
  public/images/naver-logo.png
  src/Router.js
  src/pages/Login/Login.js
  src/pages/Login/Login.scss
  src/pages/Login/LoginKakao.js
  src/pages/Login/LoginNaver.js
  src/styles/common.scss
  src/styles/reset.scss
Labels: 멘토 리뷰 요청

#5 Sign up
  src/Router.js
  src/pages/Login/LoginKakao.js
  src/pages/Login/LoginNaver.js
  src/pages/SignUp/SignUp.js
  src/pages/SignUp/SignUp.scss
Labels: 수정 요청

#8 Feature/community : community page 무한스크롤, 이미지 캐러셀 기능 구현, 댓글 기능 구현
  package-lock.json
  package.json
  public/data/commentData.json
  public/data/communityData.json
  public/images/dog.jpg
  public/images/logo.png
  src/Router.js
  src/pages/Community/Community.js
  src/pages/Community/Community.scss
  src/pages/Community/FeedAndRank/Comments/Comment/Comment.js
  src/pages/Community/FeedAndRank/Comments/Comment/Comment.scss
  src/pages/Community/FeedAndRank/Comments/CommentList/CommentList.js
  src/pages/Community/FeedAndRank/Comments/CommentList/CommentList.scss
  src/pages/Community/FeedAndRank/Comments/Comments.js
  src/pages/Community/FeedAndRank/Comments/Comments.scss
  src/pages/Community/FeedAndRank/FeedAndRank.js
  src/pages/Community/FeedAndRank/FeedAndRank.scss
  src/pages/Community/FeedAndRank/FeedList/FeedImages/FeedImages.js
  src/pages/Community/FeedAndRank/FeedList/FeedImages/FeedImages.scss
  src/pages/Community/FeedAndRank/FeedList/FeedList.js
  src/pages/Community/FeedAndRank/FeedList/FeedList.scss
  src/pages/Community/FeedAndRank/Rank/Rank.js
  src/pages/Community/FeedAndRank/Rank/Rank.scss
Labels: 멘토 리뷰 요청

#11 footer page : 멘토님 리뷰 반영 class selector 사용
  public/images/facebook-logo.png
  public/images/footer-logo.png
  public/images/insta-logo.png
  public/images/twitter-logo.png
  src/Router.js
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
Labels: 멘토 리뷰 요청

#6 Component/nav : 피드백 리뷰 반영
  public/images/Logo.png
  public/images/chatImage.png
  public/images/test.jpg
  src/Router.js
  src/components/Nav/Nav.js
  src/components/Nav/Nav.scss
  src/styles/reset.scss
Labels: 멘토 리뷰 요청

#1 Feature/subscribe : 구독 페이지 멘토님 리뷰 1차 반영 완료, 이후 fetch 연결 완료 및 코드 수정
  src/Router.js
  src/pages/Order/Order.js
  src/pages/Subscribe/Subscribe.js
  src/pages/Subscribe/Subscribe.scss
Labels: 멘토 리뷰 요청

#10 Exercise ui및 기능구현, json목데이터 연결 완료
  public/data/exercise.json
  public/images/banana.jpg
  public/images/food1.jpg
  public/images/food2.jpg
  public/images/icon-bread.png
  public/images/icon-exercise.png
  public/images/icon-lunch-sun.png
  public/images/icon-moon.png
  public/images/icon-sun.png
  src/Router.js
  src/components/DietContainer/DietContainer.js
  src/components/DietContainer/DietContainer.scss
  src/config.js
  src/pages/Exercise/Exercise.js
  src/pages/Exercise/Exercise.scss
  src/pages/Login/LoginKakao.js
  src/pages/Login/LoginNaver.js
  src/pages/SignUp/SignUp.js
Labels: Conflict 해결 요청, 수정 요청

#9 ADD : 마이페이지 작업
  package-lock.json
  package.json
  public/data/condition.json
  public/data/orders.json
  public/images/logo3.jpg
  src/Router.js
  src/components/Bar/Bar.js
  src/components/Bar/Bar.scss
  src/components/Button/Button.js
  src/components/Button/Button.scss
  src/components/Checkbox/Checkbox.js
  src/components/Checkbox/Checkbox.scss
  src/components/Input/Input.js
  src/components/Input/Input.scss
  src/components/Popup/Popup.js
  src/components/Popup/Popup.scss
  src/data/gender.js
  src/data/profileData.js
  src/data/total.js
  src/pages/MyPage/Edit/Edit.js
  src/pages/MyPage/Edit/Edit.scss
  src/pages/MyPage/Info/BuyList/BuyList.js
  src/pages/MyPage/Info/BuyList/BuyList.scss
  src/pages/MyPage/Info/Chatting/Chatting.js
  src/pages/MyPage/Info/Chatting/Chatting.scss
  src/pages/MyPage/Info/Current/Current.js
  src/pages/MyPage/Info/Current/Current.scss
  src/pages/MyPage/Info/Goal/Goal.js
  src/pages/MyPage/Info/Goal/Goal.scss
  src/pages/MyPage/Info/Info.js
  src/pages/MyPage/Info/Info.scss
  src/pages/MyPage/Info/Profile/Profile.js
  src/pages/MyPage/Info/Profile/Profile.scss
  src/pages/MyPage/Info/Rank/Rank.js
  src/pages/MyPage/Info/Rank/Rank.scss
  src/styles/common.scss
  src/styles/reset.scss
Labels: 완료

#15 hotfix / input 스크롤 넘버 버그수정
  src/components/Input/Input.js
Labels: 완료

#14 Component/nav 기능수정중
  src/components/Nav/Nav.scss
Labels: 추가 기능 구현 중

#17 fix : footer.scss 수정, footer 위치 하단에 고정
  src/components/Footer/Footer.scss
Labels: 멘토 리뷰 요청

#18 fix : common.scss 수정, footer 위치 관련해서 position 추가
  src/styles/common.scss
Labels: 멘토 리뷰 요청

#24 fix : community page footer.js 적용 높이 추가, rank mockdata 추가 및 반영, feedList 구역에만 무한 스크롤 기능 적용 및 스크롤바 커스텀 반영
  public/data/feedRank.json
  src/pages/Community/Community.js
  src/pages/Community/Community.scss
  src/pages/Community/FeedAndRank/Comments/CommentList/CommentList.scss
  src/pages/Community/FeedAndRank/Comments/Comments.js
  src/pages/Community/FeedAndRank/FeedAndRank.js
  src/pages/Community/FeedAndRank/FeedList/FeedList.js
  src/pages/Community/FeedAndRank/FeedList/FeedList.scss
  src/pages/Community/FeedAndRank/Rank/Rank.js
  src/pages/Community/FeedAndRank/Rank/Rank.scss
Labels: 멘토 리뷰 요청
